name: 'Avoid workflow being suspended'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1,15,28 * *'

jobs:
  auto_renew:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 'Generate UUID'
        run: echo $(uuidgen) > .github/UUID.txt

      - name: 'Sync before commit'
        run: git pull --rebase

      - name: 'Commit Files'
        id: commit
        run: |
          git config user.email "me@kmou424.moe"
          git config user.name "kmou424"
          git add .github/UUID.txt
          if git diff --cached --quiet; then
            echo "status=no_change" >> $GITHUB_OUTPUT
          else
            git commit -m 'update UUID'
            echo "status=success" >> $GITHUB_OUTPUT
          fi

      - name: 'GitHub Push'
        if: steps.commit.outputs.status == 'success'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
